INSERT INTO public.cidades (nome, uf_id) VALUES
('Porto Velho', 11),
('Rio Branco', 12),
('Manaus', 13),
('Boa Vista', 14),
('Belém', 15),
('Macapá', 16),
('Palmas', 17),
('São Luís', 21),
('Teresina', 22),
('Fortaleza', 23),
('Natal', 24),
('João Pessoa', 25),
('Recife', 26),
('Maceió', 27),
('Aracaju', 28),
('Salvador', 29),
('Belo Horizonte', 31),
('Vitória', 32),
('Rio de Janeiro', 33),
('São Paulo', 35),
('Curitiba', 41),
('Florianópolis', 42),
('Porto Alegre', 43),
('Campo Grande', 50),
('Cuiabá', 51),
('Goiânia', 52),
('Brasília', 53),
('Ji-Paraná', 11),
('Cruzeiro do Sul', 12),
('Parintins', 13),
('Rorainópolis', 14),
('Ananindeua', 15),
('Santana', 16),
('Araguaína', 17),
('Imperatriz', 21),
('Parnaíba', 22),
('Juazeiro do Norte', 23),
('Mossoró', 24),
('Campina Grande', 25),
('Olinda', 26),
('Arapiraca', 27),
('Nossa Senhora do Socorro', 28),
('Feira de Santana', 29),
('Uberlândia', 31),
('Vila Velha', 32),
('Niterói', 33),
('Campinas', 35),
('Londrina', 41),
('Joinville', 42),
('Caxias do Sul', 43),
('Dourados', 50),
('Várzea Grande', 51),
('Anápolis', 52);
