-- Criação da tabela principal de Vendas (Cabeçalho)
CREATE TABLE vendas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_venda TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    cliente_nome VARCHAR(255),
    valor_total DECIMAL(19, 2) NOT NULL,
    usuario_nome VARCHAR(255),
    CONSTRAINT pk_vendas PRIMARY KEY (id)
);

-- Criação da tabela secundária de Itens da Venda (Relacionamento)
CREATE TABLE itens_venda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    venda_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    quantidade INTEGER NOT NULL,
    preco_unitario DECIMAL(19, 2) NOT NULL,
    subtotal DECIMAL(19, 2) NOT NULL,
    CONSTRAINT pk_itens_venda PRIMARY KEY (id)
);

-- Definição das Chaves Estrangeiras (Foreign Keys) para integridade do banco
ALTER TABLE itens_venda 
    ADD CONSTRAINT fk_itens_venda_on_venda FOREIGN KEY (venda_id) REFERENCES vendas (id) ON DELETE CASCADE;

ALTER TABLE itens_venda 
    ADD CONSTRAINT fk_itens_venda_on_produto FOREIGN KEY (produto_id) REFERENCES produtos (id);
