-- 1. Criação da tabela de clientes
CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome VARCHAR(255) NOT NULL,
    CONSTRAINT pk_clientes PRIMARY KEY (id)
);

-- 2. Inserção obrigatória do Cliente Padrão para vendas rápidas
INSERT INTO clientes (id, nome) VALUES (1, 'Cliente Padrão');

-- 3. Adiciona a coluna de relacionamento na tabela de vendas
ALTER TABLE vendas ADD COLUMN cliente_id BIGINT;

-- 4. Cria a constraint de chave estrangeira (Foreign Key)
ALTER TABLE vendas 
    ADD CONSTRAINT fk_vendas_on_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id);
