ALTER TABLE clientes
ADD COLUMN telefone VARCHAR(20) NULL;

ALTER TABLE clientes
ADD COLUMN email VARCHAR(255) NULL UNIQUE;

ALTER TABLE clientes 
ADD COLUMN data_atualizacao TIMESTAMP NOT NULL DEFAULT NOW();

