CREATE TABLE unidades_federativas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sigla VARCHAR(2) NOT NULL UNIQUE,
    nome VARCHAR(255) NOT NULL
);

CREATE TABLE cidades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    uf_id BIGINT NOT NULL,

    CONSTRAINT fk_unidades_federativas
        FOREIGN KEY (uf_id)
        REFERENCES unidades_federativas (id)
        ON DELETE CASCADE
);

CREATE TABLE fornecedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    email VARCHAR(255) UNIQUE,
    telefone VARCHAR(20),
    cnpj VARCHAR(18) UNIQUE,
    endereco VARCHAR(255),
    cidade_id BIGINT NOT NULL,
    cep VARCHAR(9),
    observacao VARCHAR(500),
    data_criacao timestamp,
    data_atualizacao timestamp,
    CONSTRAINT fk_cidade
        FOREIGN KEY (cidade_id)
        REFERENCES cidades (id)
        ON DELETE CASCADE
);